spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apishop
    username: maven
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate :
      ddl-auto: create
